mandatoryAccounts:
  - name: Management
    description: Management Account
    email: wemistic@gmail.com
    organizationalUnit: Root
  - name: LogArchive
    description: Log Archive Account
    email: wemistic.1@gmail.com
    organizationalUnit: Security
  - name: Audit
    description: Audit Account
    email: wemistic.2@gmail.com
    organizationalUnit: Security

workloadAccounts: []
