mandatoryAccounts:
  - name: Management
    description: Management Account
    email: management@example.com
  - name: LogArchive
    description: Log Archive Account
    email: logarchive@example.com
  - name: Audit
    description: Audit Account
    email: audit@example.com

workloadAccounts: []
