homeRegion: us-east-1
enabledRegions:
  - us-east-1
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 365

logging:
  account: LogArchive
  s3:
    retentionInDays: 365

controlTower:
  enable: false
  landingZone:
    version: "3.0"
    logging:
      loggingBucketRetentionDays: 365
    security:
      kmsKeyArn: ""
