cloudWatch:
  enable: true
  alarmSets: []
  metricSets: []

accessAnalyzer:
  enable: false

iamPasswordPolicy:
  allowUsersToChangePassword: true
  hardExpiry: false
  requireUppercaseCharacters: true
  requireLowercaseCharacters: true
  requireSymbols: true
  requireNumbers: true
  minimumPasswordLength: 14
  passwordReusePrevention: 24
  maxPasswordAge: 90

awsConfig:
  enable: false
  enableConfigurationRecorder: false

centralSecurityServices:
  delegatedAdminAccount: Audit

  ebsDefaultVolumeEncryption:
    enable: false

  s3PublicAccessBlock:
    enable: true

  guardduty:
    enable: false

    s3Protection:
      enable: false

    exportConfiguration:
      enable: false
      destinationType: S3
      exportFrequency: MONTHLY
      kmsKeyArn: ""

  securityHub:
    enable: false
    regionAggregation: false
    standards: []

  ssmAutomation:
    enable: false
    documentSets: []
